syntax on
filetype plugin indent on

set expandtab
set tabstop=2 shiftwidth=2 softtabstop=2
set shiftround
set autoindent
set smartindent

set number relativenumber numberwidth=5
set laststatus=2
set noequalalways

if has('gui_running')
  set guioptions=agic
  set guifont=Hack\ 12
endif

let s:vim_home = fnamemodify($MYVIMRC, ':p:h')

let s:plug_file = expand(s:vim_home..'/autoload/plug.vim')
if empty(glob(s:plug_file))
  let s:curl = 'curl'
  if has('win32')
    let s:curl ..= '.exe'
  endif
  silent execute '!' .. s:curl .. ' -fLo ' .. s:plug_file .. ' --create-dirs https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim'
  autocmd VimEnter * PlugInstall --sync | source $MYVIMRC
endif

let &backupdir = join([s:vim_home .. '/tmp', '~/tmp'], ',')
let &directory = join([s:vim_home .. '/tmp', '~/tmp'], ',')

call plug#begin()

Plug 'tpope/vim-surround'
Plug 'tmsvg/pear-tree'
let g:pear_tree_ft_disabled = ['vim']
let g:pear_tree_smart_openers = 1
let g:pear_tree_smart_closers = 1
let g:pear_tree_smart_backspace = 1
augroup scheme_pear_tree
  autocmd!
  autocmd FileType scheme,racket let b:pear_tree_pairs = {
        \ '(': {'closer': ')'},
        \ '[': {'closer': ']'},
        \ '"': {'closer': '"'},
        \}
augroup end
Plug 'justinmk/vim-sneak'
let g:sneak#label = v:true
Plug 'tpope/vim-commentary'
" Plug 'junegunn/rainbow_parentheses.vim'
" let g:rainbow#max_level = 16
Plug 'luochen1990/rainbow'
let g:rainbow_conf = {
      \ 'guifgs': ['white', 'orange', 'red', 'green', 'yellow', 'magenta', 'cyan'],
      \ 'ctermfgs': ['white', 'blue', 'red', 'green', 'yellow', 'magenta', 'cyan'],
      \}
augroup rainbow_activation
  autocmd!
  " autocmd FileType clojure,scheme RainbowParentheses
  autocmd FileType scheme,racket RainbowToggle
augroup end

Plug 'morhetz/gruvbox'
" let g:gruvbox_italic=1

Plug 'axvr/zepl.vim'
let g:repl_config = {
      \ 'racket': { 'cmd': 'racket' },
      \}

Plug 'bhurlow/vim-parinfer'
let g:vim_parinfer_filetypes = ['scheme']

Plug 'benknoble/vim-racket'

call plug#end()

set hidden

" set termguicolors
set background=dark
colorscheme gruvbox

set nowrap
let &listchars = join(["tab:\u00bb ", "trail:\u00b7", "precedes:\u27ea", "extends:\u27eb"], ',')
let &fillchars ..= ",vert: "
highlight! link VertSplit StatusLine
set list
set scrolloff=3
set sidescrolloff=6
set sidescroll=1
augroup color_column
  autocmd!
  autocmd BufNewFile,BufRead,BufWinEnter,WinEnter *
        \ if &filetype != 'help' |
        \ let &l:colorcolumn = join(insert(range(120, 999), 80), ',') |
        \ else |
        \ let &l:colorcolumn = '' |
        \ endif
  autocmd WinLeave * let &l:colorcolumn = join(range(1, 999), ',')
augroup end
augroup cursor_line
  autocmd!
  autocmd BufNewFile,BufRead,BufWinEnter,WinEnter *
        \ if &filetype != 'help' |
        \ let &l:cursorline = !&diff |
        \ else |
        \ let &l:cursorline = 0 |
        \ endif
  autocmd OptionSet diff let &l:cursorline = !v:option_new
  autocmd WinLeave * setlocal nocursorline
augroup end
" open quickfix window always at the bottom of all windows
augroup quickfix_window
  autocmd!
  autocmd FileType qf wincmd J
augroup end

tnoremap <esc> <c-\><c-n>

if !has("gui_running")
  execute "set <a-h>=\eh"
  execute "set <a-j>=\ej"
  execute "set <a-k>=\ek"
  execute "set <a-l>=\el"
endif
nnoremap <a-h> <c-w>h
nnoremap <a-j> <c-w>j
nnoremap <a-k> <c-w>k
nnoremap <a-l> <c-w>l
inoremap <a-h> <c-\><c-n><c-w>h
inoremap <a-j> <c-\><c-n><c-w>j
inoremap <a-k> <c-\><c-n><c-w>k
inoremap <a-l> <c-\><c-n><c-w>l
vnoremap <a-h> <c-w>h
vnoremap <a-j> <c-w>j
vnoremap <a-k> <c-w>k
vnoremap <a-l> <c-w>l
tnoremap <a-h> <c-w>h
tnoremap <a-j> <c-w>j
tnoremap <a-k> <c-w>k
tnoremap <a-l> <c-w>l

noremap H ^
noremap L $
nnoremap <backspace> <c-^>

function! s:insert_put()
  let keys = "\<esc>g"
  if col(".") == 1
    let keys ..= 'P'
  else
    let keys ..= 'p'
  endif
  if col('.') == col('$')
    let keys ..= 'a'
  else
    let keys ..= 'i'
  endif
  return keys
endfunction
inoremap <expr> <a-v> <sid>insert_put()
tnoremap <c-v> <c-\><c-n>"+pa

function! s:empty_lines(count, above)
  let current_position = getcurpos()
  let new_position = [current_position[1], current_position[4]]
  let line_to_insert = new_position[0]
  if a:above
    let line_to_insert = new_position[0] - 1
    let new_position[0] += a:count
  endif
  call append(line_to_insert, repeat([''], a:count))
  call cursor(new_position)
endfunction
nnoremap <silent> [<cr> :<c-u>call <sid>empty_lines(v:count1, v:true)<cr>
nnoremap <silent> ]<cr> :<c-u>call <sid>empty_lines(v:count1, v:false)<cr>

" automatically replace tabs with spaces on saving
" set g:autoretab to false to turn off this behavior
let g:autoretab = v:true
" ...or invoke this command to toggle option
command! AutoRetabToggle let g:autoretab = !g:autoretab
augroup auto_retab
  autocmd!
  autocmd BufWrite * if g:autoretab | retab | endif
augroup end
" automatically remove trailing spaces
" set g:autoremove_trail_spaces to false to turn off this behavior
let g:autoremove_trail_spaces = v:true
" ...or invoke this command to toggle option
command! AutoRemoveTrailSpaceToggle let g:autoremove_trail_spaces = !g:autoremove_trail_spaces
augroup auto_remove_trail_space
  autocmd!
  function! s:remove_trail_space()
    let view = winsaveview()  " store view to avoid cursor movement to last removed trailing space position
    try
      %s/\v\s+$//
    catch /E486:/  " no trailing spaces found, suppress error message
    endtry
    call winrestview(view)  " restore window view
  endfunction
  autocmd BufWrite * if g:autoremove_trail_spaces | call <sid>remove_trail_space() | endif
augroup end

set incsearch
set ignorecase
set smartcase
" highlight matches only during searching
augroup searching_highlight
  autocmd!
  set nohlsearch
  autocmd CmdlineEnter /,\? set hlsearch
  autocmd CmdlineLeave /,\? set nohlsearch
augroup end
" easier searching of visually selected text
vnoremap <c-s> y/<c-r>"<cr>

" statusline
function! s:cwd()
  if index(['help'], &filetype) < 0
    let cwd = fnamemodify(getcwd(), ':~')
    return pathshorten(cwd) .. ': '
  endif
  return ''
endfunction
function! s:relative_file_path()
  let full_cwd = escape(fnamemodify(getcwd(), ':p'), '\%')
  let bufname_full = fnamemodify(bufname(), ':p')
  let relative_path = matchstr(bufname_full, '\v^' .. full_cwd .. '\zs.*$')
  if strlen(relative_path) == 0
    let relative_path = bufname_full
  endif
  let relative_dir = fnamemodify(relative_path, ':h')
  if relative_dir =~ '\v^' .. expand("$HOME")
    let relative_dir = substitute(relative_dir, '\v^' .. expand("$HOME"), '~', '')
  endif
  let filename = fnamemodify(bufname_full, ':t')
  if empty(filename)
    return '[No Name]'
  endif
  if relative_dir == '.'
    return filename
  else
    return pathshorten(relative_dir) .. '/' .. filename
  endif
endfunction
let &statusline="%{" .. expand("<SID>") .. "cwd()" .. "}%{" .. expand("<SID>") .. "relative_file_path()} %m"
