colorscheme gruvbox-dark
set global scrolloff 2,4
set global indentwidth 2

map global normal = '|fmt -w $kak_opt_autowrap_column<ret>'

# Clipboard interaction (via xclip)
map global normal <c-y> '<a-|>xclip -selection clipboard<ret>'
map global normal <c-v> '!xclip -out -selection clipboard<ret>'

# Line numbers
add-highlighter -override global/ number-lines -relative -hlcursor

# <c-j> and <c-k> for selecting completion candidate
hook global InsertCompletionShow .* %{
  map window insert <ret> <c-n>
  map window insert <c-k> <c-p>
}
hook global InsertCompletionHide .* %{
  unmap window insert <ret> <c-n>
  unmap window insert <c-k> <c-p>
}

# expand tab with proper number of spaces, no softtabstop
hook global InsertChar \t %{
  try %{
    execute-keys -draft "h<a-h><a-k>\A\h+\z<ret><a-;>;%opt{indentwidth}@"
  }
}
hook global InsertDelete ' ' %{
  try %{
    execute-keys -draft 'h<a-h><a-k>\A\h+\z<ret>i<space><esc><lt>'
  }
}

# use ripgrep for grepping
set global grepcmd 'rg -n'

remove-hooks global python
hook global WinSetOption filetype=python %{
    set-option window lintcmd %{ run() { pylint --msg-template='{path}:{line}:{column}: {category}: {msg_id}: {msg} ({symbol})' "$1" | awk -F: 'BEGIN { OFS=":" } { if (NF == 6) { $3 += 1; print } }'; } && run }
}
