customCommands:
  - key: 'P'
    description: "Push"
    context: 'global'
    loadingText: 'Pushing...'
    prompts:
      - type: 'menu'
        title: 'How to push?'
        options:
          - value: 'push'
          - value: 'push --force'
          - value: 'push --force-with-lease'
          - value: 'push --set-upstream origin {{.CheckedOutBranch.Name}}'
    command: "git {{index .PromptResponses 0}}"
gui:
  theme:
    selectedLineBgColor:
      - "#3f5865"
