theme = "boo_berry"

[editor]
line-number = "relative"
rulers = [150]
color-modes = true
scrolloff = 3
cursorline = true

[editor.cursor-shape]
insert = "bar"

[editor.statusline]
right = ["diagnostics", "position", "position-percentage"]
