theme = "everforest_dark"

[editor]
line-number = "relative"
color-modes = true

[editor.statusline]
left = ["mode", "spinner", "version-control"]
center = ["file-name", "read-only-indicator", "file-modification-indicator"]
right = ["diagnostics", "selections", "register", "position", "position-percentage", "file-encoding"]

[editor.lsp]
display-inlay-hints = true
auto-signature-help = false

[editor.cursor-shape]
insert = "bar"

[editor.file-picker]
hidden = false

[keys.normal]
C-e = [":new", ":insert-output lf --print-selection", ":redraw", "goto_file"]
A-h = "select_prev_sibling"
A-j = "shrink_selection"
A-k = "expand_selection"
A-l = "select_next_sibling"
