theme = "everforest_dark"

[editor]
line-number = "relative"
color-modes = true

[editor.statusline]
left = ["mode", "spinner", "version-control"]
center = ["file-name", "read-only-indicator", "file-modification-indicator", "file-type"]
right = ["diagnostics", "selections", "register", "position", "position-percentage", "file-encoding"]

[editor.lsp]
display-inlay-hints = true
auto-signature-help = false

[editor.cursor-shape]
insert = "bar"
select = "underline"

[editor.file-picker]
hidden = false

[keys.normal]
"esc" = ["collapse_selection", "keep_primary_selection"]

# textobject-based (sticky) menus
[keys.normal.f]
label = "Character search mode"
h = "find_prev_char"
j = "find_till_char"
k = "till_prev_char"
l = "find_next_char"

[keys.normal.F]
label = "Character extend search mode"
h = { label = "Extend to previous occurence of char", command = ["select_mode", "extend_prev_char"]}
j = { label = "Extend till previous occurence of char", command = ["select_mode", "extend_till_char"]}
k = { label = "Extend to next occurence of char", command = ["select_mode", "extend_till_prev_char"]}
l = { label = "Extend till next occurence of char", command = ["select_mode", "extend_next_char"]}

[keys.normal.w]
label = "Word mode"
w = { label = "Select current word", command = ["select_textobject_inner", "@w*w"]}
k = { label = "Move to previous word", command = ["move_prev_word_start", "@w"]}
j = { label = "Move to next word", command = ["move_next_word_start", "@w"]}
h = { label = "Move to previous WORD", command = ["move_prev_long_word_start", "@w"]}
l = { label = "Move to next WORD", command = ["move_next_long_word_start", "@w"]}
K = { label = "Extend to previous word", command = ["select_mode", "extend_prev_word_start", "@w"]}
J = { label = "Extend to next word", command = ["select_mode", "extend_next_word_start", "@w"]}
H = { label = "Extend to previous WORD", command = ["select_mode", "extend_prev_long_word_start", "@w"]}
L = { label = "Extend to next WORD", command = ["select_mode", "extend_next_long_word_start", "@w"]}
i = "insert_mode"
a = "append_mode"
s = "select_regex"
c = "change_selection"
d = "delete_selection"
backspace = { label = "Delete previous word", command = ["delete_word_backward", "@w"]}
del = { label = "Delete next word", command = ["delete_word_forward", "@w"]}
f = { label = "Character search mode", command = ["normal_mode", "@f"]}
g = { label = "Jump to word", command = ["no_op", "goto_word"]}
G = { label = "Extend to word", command = ["select_mode", "extend_to_word"]}

[keys.select.w]
label = "Word mode"
space = { label = "Exit select mode", command = ["exit_select_mode", "@w"]}
w = { label = "Select current word", command = ["select_textobject_inner", "@w*w"]}
k = { label = "Extend to previous word", command = ["extend_prev_word_start", "@w"]}
j = { label = "Extend to next word", command = ["extend_next_word_start", "@w"]}
h = { label = "Extend to previous WORD", command = ["extend_prev_long_word_start", "@w"]}
l = { label = "Extend to next WORD", command = ["extend_next_long_word_start", "@w"]}
K = { label = "Extend to previous word", command = ["extend_prev_word_start", "@w"]}
J = { label = "Extend to next word", command = ["extend_next_word_start", "@w"]}
H = { label = "Extend to previous WORD", command = ["extend_prev_long_word_start", "@w"]}
L = { label = "Extend to next WORD", command = ["extend_next_long_word_start", "@w"]}
s = "select_regex"
c = "change_selection"
d = "delete_selection"
backspace = { label = "Delete previous word", command = ["delete_word_backward", "@w"]}
del = { label = "Delete next word", command = ["delete_word_forward", "@w"]}
f = { label = "Character search mode", command = ["normal_mode", "@F"]}
g = { label = "Extend to word", command = ["no_op", "extend_to_word"]}

# integrations with external tools via Tmux
[keys.normal."C-e"]
label = "External tools"
g = { label = "Open lazygit", command = ":run-shell-command tmux split-pane -l 75% lazygit -w $(git rev-parse --show-toplevel)" }
l = { label = "Select files with lf", command = ":run-shell-command helix_pid=\"$(ps -o ppid= $$)\" ~/.config/helix/hxlf" }
A-l = { label = "Open files selected with lf", command = [":new", ":insert-output cat ~/.cache/hxlf/selected", "split_selection_on_newline", "goto_file", "goto_last_modified_file", ":buffer-close!"] }

[keys.select."C-e"]
label = "External tools"
g = { label = "Open lazygit", command = ":run-shell-command tmux split-pane -l 75% lazygit -w $(git rev-parse --show-toplevel)" }
l = { label = "Select files with lf", command = ":run-shell-command helix_pid=\"$(ps -o ppid= $$)\" ~/.config/helix/hxlf" }
A-l = { label = "Open files selected with lf", command = [":new", ":insert-output cat ~/.cache/hxlf/selected", "split_selection_on_newline", "goto_file", "goto_last_modified_file", ":buffer-close!"] }

# TESTS
# sticky mode
# X = "extend_line" # both directions!
# [keys.normal."'"]
# h = { label = "Go left with macro", command = ["move_char_left", "@'"] }

