theme = "everforest_dark"

[editor]
line-number = "relative"
color-modes = true

[editor.statusline]
left = ["mode", "spinner", "version-control"]
center = ["file-name", "read-only-indicator", "file-modification-indicator"]
# add language (servers)
right = ["diagnostics", "selections", "register", "position", "position-percentage", "file-encoding"]

[editor.lsp]
display-inlay-hints = true
auto-signature-help = false

[editor.cursor-shape]
insert = "bar"

[editor.file-picker]
hidden = false

[keys.normal]
"esc" = ["collapse_selection", "keep_primary_selection"]
# Tmux+Broot integration
# C-e = ":run-shell-command tmux split-pane -h -e helix_tmux_pane=$TMUX_PANE broot"
# C-x = ":run-shell-command tmux split-pane -h -e EDITOR=\"tmux send-keys -t $TMUX_PANE :e Space \" broot"
# Tmux+Lazygit integration
C-g = ":run-shell-command tmux display-popup -E -h 90% -w 90% lazygit -w $(pwd)"
A-h = "select_prev_sibling"
A-j = "shrink_selection"
A-k = "expand_selection"
A-l = "select_next_sibling"
H = ["select_mode", "extend_char_left"]
J = ["select_mode", "extend_line_down"]
K = ["select_mode", "extend_line_up"]
L = ["select_mode", "extend_char_right"]
C-j = "join_selections"
C-A-j = "join_selections_space"
C-k = "keep_selections"
C-A-k = "remove_selections"
X = ["select_mode", "extend_line_below"]
q = "move_prev_word_start"
Q = ["select_mode", "extend_prev_word_start"]
b = "replay_macro"
B = "record_macro"
w = "@miw*"
W = "no_op"
E = ["select_mode", "extend_next_word_end"]
A-q = "move_prev_long_word_start"
A-Q = ["select_mode", "extend_prev_long_word_start"]
A-w = "@miw"
A-e = "move_next_long_word_end"
A-E = ["select_mode", "extend_next_long_word_end"]
F = ["select_mode", "extend_next_char"]
T = ["select_mode", "extend_till_char"]
A-f = "find_prev_char"
A-F = ["select_mode", "extend_prev_char"]
A-t = "till_prev_char"
A-T = ["select_mode", "extend_till_prev_char"]
[keys.normal.G]
g = ["select_mode", "goto_file_start"]
e = ["select_mode", "goto_last_line"]
h = ["select_mode", "goto_line_start"]
l = ["select_mode", "goto_line_end"]
s = ["select_mode", "goto_first_nonwhitespace"]
t = ["select_mode", "goto_window_top"]
c = ["select_mode", "goto_window_center"]
b = ["select_mode", "goto_window_bottom"]
"." = ["select_mode", "goto_last_modification"]
j = ["select_mode", "extend_visual_line_down"]
k = ["select_mode", "extend_visual_line_up"]
w = ["select_mode", "extend_to_word"]
[keys.normal.m]
M = ["select_mode", "match_brackets"]
# LF (selecting multiple files and browsing file tree) integration
[keys.normal.space]
C-e = ":run-shell-command helix_pid=\"$(ps -o ppid= $$)\" ~/.config/helix/hxlf"
[keys.normal.g]
C-e = [":open ~/.cache/hxlf/selected", "select_all", "split_selection_on_newline", "goto_file", ":open ~/.cache/hxlf/selected", ":buffer-close!"]

[keys.select]
"esc" = ["normal_mode", "collapse_selection", "keep_primary_selection"]
H = "extend_char_left"
J = "extend_line_down"
K = "extend_line_up"
L = "extend_char_right"
C-j = "join_selections"
C-A-j = "join_selections_space"
C-k = "keep_selections"
C-A-k = "remove_selections"
X = "extend_line_below"
q = "extend_prev_word_start"
Q = "extend_prev_word_start"
b = "replay_macro"
B = "record_macro"
w = "@miw*"
W = "no_op"
E = "extend_next_word_end"
A-q = "extend_prev_long_word_start"
A-Q = "extend_prev_long_word_start"
A-w = "@miw"
A-e = "move_next_long_word_end"
A-E = "extend_next_long_word_end"
F = "extend_next_char"
T = "extend_till_char"
A-f = "extend_prev_char"
A-F = "extend_prev_char"
A-t = "extend_till_prev_char"
A-T = "extend_till_prev_char"
